<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.github.msx80.omicron</groupId>
  <artifactId>web-wrapper</artifactId>
  <version>1.0.0</version>
  
  	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
	</properties>
  
  <dependencies>
  <!-- TODO see if we can do without -->
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.22.0</version>
    <scope>compile</scope>
</dependency>
<!-- logs something during build
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>2.0.17</version>
</dependency>-->
	<dependency>
	    <groupId>com.github.xpenatan.gdx-teavm</groupId>
	    <artifactId>backend-web</artifactId>
	    <version>1.6.1</version>
	</dependency>
	<dependency>
		<artifactId>omicron-engine</artifactId>
		<groupId>com.github.msx80.omicron</groupId>
		<version>0.0.13-SNAPSHOT</version>	
 		<exclusions>
                <exclusion>
        <groupId>com.github.msx80</groupId>
  <artifactId>wiseloader</artifactId>
        </exclusion>
            </exclusions>		
	</dependency>

<dependency>
	<artifactId>${cartridge.artifactId}</artifactId>
	<groupId>${cartridge.groupId}</groupId>
	<version>${cartridge.version}</version>
</dependency>


  </dependencies>
  	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<mainClass></mainClass>
					<executable>java</executable>
			        <arguments>
			            <argument>-classpath</argument>
			            <classpath/>
			            <argument>omicron.teavm.TeaBuild</argument>
			        </arguments>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>exec</goal>
						</goals>
					</execution>
				</executions>				
			</plugin>	
		</plugins>
  	</build>
  
</project>
