# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Omicron Player
      run: |
        cd omicron-player
        chmod +x gradlew
        ./gradlew build dist
    - name: Build Hello World cart
      run: |
        cd demo/HelloWorld
        chmod +x gradlew
        ./gradlew build
    - name: Build Snake cart
      run: |
        cd demo/Snake
        chmod +x gradlew
        ./gradlew build
    - name: Build Android Player
      run: |
        cd android
        chmod +x gradlew
        ./gradlew clean android:assembleDebug
    - name: Deploy Player
      uses: actions/upload-artifact@v2
      with:
        name: 'OmicronPlayer.jar'
        path: omicron-player/OmicronPlayer.jar       
    - name: Deploy HelloWorld Demo
      uses: actions/upload-artifact@v2
      with:
        name: 'HelloWorld.omicron'
        path: demo/HelloWorld/HelloWorld.omicron
    - name: Deploy Snake Demo
      uses: actions/upload-artifact@v2
      with:
        name: 'SnakeMain.omicron'
        path: demo/Snake/SnakeMain.omicron
