# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Omicron Player
      run: |
        cd omicron-player
        mvn --batch-mode clean compile install package
    - name: Build Hello World cart
      run: |
        cd demo/HelloWorld
        chmod +x gradlew
        ./gradlew build
    - name: Build FeatureDemo cart
      run: |
        cd demo/FeatureDemo
        mvn --batch-mode clean compile install package
    - name: Build FeatureDemoStandalone
      run: |
        cd demo/FeatureDemoStandalone
        mvn --batch-mode clean compile install package
    - name: Build AlienBuster cart
      run: |
        cd demo/AlienBuster
        chmod +x gradlew
        ./gradlew build
    - name: Build Retrodrawing cart
      run: |
        cd demo/Retrodrawing
        chmod +x gradlew
        ./gradlew build
    - name: Build Snake cart
      run: |
        cd demo/Snake
        chmod +x gradlew
        ./gradlew build
    - name: Build Android Player
      run: |
        cd android
        chmod +x gradlew
        ./gradlew clean android:assembleDebug
    - name: Deploy Player
      uses: actions/upload-artifact@v2
      with:
        name: 'OmicronPlayer.jar'
        path: omicron-player/OmicronPlayer.jar       
    - name: Deploy HelloWorld Demo
      uses: actions/upload-artifact@v2
      with:
        name: 'HelloWorld.omicron'
        path: demo/HelloWorld/HelloWorld.omicron
    - name: Deploy FeatureDemo Demo
      uses: actions/upload-artifact@v2
      with:
        name: 'FeatureDemo.omicron'
        path: demo/FeatureDemo/FeaturesDemo.omicron
    - name: Deploy Snake Demo
      uses: actions/upload-artifact@v2
      with:
        name: 'SnakeMain.omicron'
        path: demo/Snake/SnakeMain.omicron
    - name: Deploy AlienBuster Demo
      uses: actions/upload-artifact@v2
      with:
        name: 'AlienBusterGame.omicron'
        path: demo/AlienBuster/AlienBusterGame.omicron
    - name: Deploy Retrodrawing Demo
      uses: actions/upload-artifact@v2
      with:
        name: 'RetroDrawer.omicron'
        path: demo/Retrodrawing/RetroDrawer.omicron
