name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - name: make
      run: |
        sudo apt-get install mesa-common-dev
        cd libretro/LibretroOmicronCore
        make all
